### PR TITLE
Issue #9

### PR DESCRIPTION
**Pull request by ljacomet**
Add repository information to enable community builds

### CODE REVIEW

**Comment by myronkscott** [comment]
What about the version of terracotta-parent?  Should that change to 5.0-SNAPSHOT?

**Comment by ljacomet** [comment]
I'd rather stick with released version. As indicated in terracotta-oss/terracotta-parent#5, there will be an upcoming 5.0.0.alpha2 that I will include in this PR.

**Comment by ljacomet** [comment]
test this please

**Comment by jd0-sag** [comment]
This exposed an indirect dependency on Guava, in a downstream project.  That has now been made direct so this can merge.

**Pull request merged**
