### PR TITLE
Issue #263 : Enforce non-nullness of entity information in entity exceptions

### PR DESCRIPTION
**Pull request by chrisdennis**

### CODE REVIEW

**Comment by ljacomet** [comment]
Might be worth fixing that on both `release/1.3` and `master`

**Comment by chrisdennis** [comment]
@myronkscott @cschanck thoughts on this?  If you are okay with the principle here I'll convert it in to a proper daggy fix.

**Comment by myronkscott** [comment]
I don't think this is a good idea to port back to 1.3.  It is a HUGE implementation change and might involve message changes.

**Comment by chrisdennis** [comment]
Is it good for 1.4 though?

**Comment by myronkscott** [comment]
I hope so but I need some time to investigate.  The first place I spot checked looked like a complicated change which inspired the last comment.

**Comment by chrisdennis** [comment]
@myronkscott any good news to tell me?

**Comment by myronkscott** [comment]
@chrisdennis this will be handled via implementation in terracotta-core and available in the next release.

**Comment by myronkscott** [comment]
addressed by Terracotta-OSS/terracotta-core#726

**Pull request closed without merging**
